# version: '3.8'

services:
  nginx :
    build : requirements/nginx/.
    container_name : nginx
    ports : 
      - "443:443"
    volumes:
      - ./web:/var/www/html
    env_file : 
      .env


  wordpress:
    build : requirements/wordpress/.
    container_name: wordpress
    volumes:
      - ./web:/var/www/html
    env_file : 
      .env
    
  mariadb :
    container_name: mariadb
    build: requirements/mariadb/.
    env_file : 
      .env
