
services:
  mariadb:
    container_name: mariadb
    build: requirements/mariadb/.
    image : mariadb
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always
  
  wordpress:
    build : requirements/wordpress/.
    depends_on :
      - mariadb
    container_name: wordpress
    image : wordpress
    volumes:
      - wordpress_data:/var/www/html
    env_file : 
      .env
    networks:
      - inception
    restart: always

  nginx :
    build : requirements/nginx/.
    depends_on :
      - wordpress
    container_name : nginx
    image : nginx
    ports : 
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    env_file : 
      .env
    networks:
      - inception
    restart: always

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/zmoumni/data/wordpress
  mariadb_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/zmoumni/data/mariadb

networks:
  inception:
    driver: bridge